$ cat kubespray/inventory/mycluster/hosts.yaml
all:
  hosts:
    node1:
      ansible_host: 10.129.0.5
      ip: 10.129.0.5
      access_ip: 10.129.0.5
    node2:
      ansible_host: 10.129.0.7
      ip: 10.129.0.7
      access_ip: 10.129.0.7
    node3:
      ansible_host: 10.129.0.30
      ip: 10.129.0.30
      access_ip: 10.129.0.30
    node4:
      ansible_host: 10.129.0.19
      ip: 10.129.0.19
      access_ip: 10.129.0.19
    node5:
      ansible_host: 10.129.0.6
      ip: 10.129.0.6
      access_ip: 10.129.0.6
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}