apiVersion: v1
kind: Service
metadata:
  name: svc-dep-12-4-2
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: svc-nginx-http
    protocol: TCP
    port: 9001
    targetPort: nginx-http
    nodePort: 30081
  - name: svc-multitool-http
    protocol: TCP
    port: 9002
    targetPort: multitool-http
    nodePort: 30082