---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse
  post_tasks:
    - name: Clickhouse | Wait for server start
      ansible.builtin.wait_for:
        port: 9000
        delay: 30
    - name: Clickhouse | Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role
