---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.143.2
      ansible_ssh_user: vagrant
      
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.26.164
      ansible_ssh_user: vagrant

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.17.22
      ansible_ssh_user: vagrant
