{
 "title": "Nodeexporter Metrics",
 "time": { "from": "2023-07-26T16:38:57.493Z", "to": "2023-07-26T17:24:47.181Z" },
 "panels": [
  {
   "title": "RAM",
   "type": "graph",
   "description": "Количество свободной оперативной памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"} / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "description": "Количество места на файловой системе",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"nodeexporter\",mountpoint=\"/\"} / (1024 * 1024 * 1024)"
    }
   ]
  }
 ]
}