apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nodelog
          readOnly: true
          mountPath: /var/log/host_syslog
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nodelog
        hostPath:
          path: /var/log/syslog
          type: File